"""Tasks table

Revision ID: 17085aa2fcff
Revises: 
Create Date: 2018-09-15 09:18:31.357016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17085aa2fcff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('scheduledDateTime', sa.DateTime(), nullable=True),
    sa.Column('completionDateTime', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(length=140), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('reminder', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_completionDateTime'), 'tasks', ['completionDateTime'], unique=False)
    op.create_index(op.f('ix_tasks_scheduledDateTime'), 'tasks', ['scheduledDateTime'], unique=False)
    op.create_index(op.f('ix_tasks_timestamp'), 'tasks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_timestamp'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_scheduledDateTime'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completionDateTime'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
